services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/lost_and_found.sqlite:/app/lost_and_found.sqlite
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    restart: unless-stopped
